service: shop-backend

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

functions:
  getProductsList:
    handler: products.getProductsList
    events:
      - http:
          path: /products
          method: get
          cors: true
  getProductsById:
    handler: products.getProductsById
    events:
      - http:
          path: /products/{productId}
          method: get
          cors: true
