GET https://kras7hnycg.execute-api.ap-south-1.amazonaws.com/dev/products

###

GET https://kras7hnycg.execute-api.ap-south-1.amazonaws.com/dev/products/7567ec4b-b10c-48c5-9345-fc73c48a80aa

###

GET https://kras7hnycg.execute-api.ap-south-1.amazonaws.com/dev/products/74144640-4c6f-11ed-8b82-553a1dee0a14

###

POST https://kras7hnycg.execute-api.ap-south-1.amazonaws.com/dev/products
Content-Type: application/json

{
    "description": "6.1-inch (15.5 cm diagonal) Super Retina XDR display",
    "price": 1200,
    "title": "Yphone 12"
}

###


