GET https://n1yh9xjrcj.execute-api.ap-south-1.amazonaws.com/dev/products

###

GET https://n1yh9xjrcj.execute-api.ap-south-1.amazonaws.com/dev/products/7567ec4b-b10c-48c5-9345-fc73c48a80aa

###

GET https://n1yh9xjrcj.execute-api.ap-south-1.amazonaws.com/dev/products/7567ec4b-b10c-48c5-9345-fc73c48a80ab

###

POST https://n1yh9xjrcj.execute-api.ap-south-1.amazonaws.com/dev/products
Content-Type: application/json

{
    "description": "Testing",
    "price": 1200,
    "title": "Yphone 12"
}

###


