service: import-service

frameworkVersion: "3"

provider:
  name: aws
  region: ap-south-1
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: "*"
  environment:
    S3_BUCKET: "node-aws-images"

functions:
  importProductsFile:
    handler: importProductsFile.importProductsFile
    events:
      - http:
          path: /import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: importFileParser.importFileParser
    events:
      - s3:
          bucket: ${self:provider.environment.S3_BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
