service: import-service

frameworkVersion: "3"

provider:
  name: aws
  region: ap-south-1
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: "*"
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource: arn:aws:sqs:ap-south-1:792855711714:catalogItemsQueue
  environment:
    S3_BUCKET: "node-aws-images"
    SQS_URL: "https://sqs.ap-south-1.amazonaws.com/792855711714/catalogItemsQueue"

functions:
  importProductsFile:
    handler: importProductsFile.importProductsFile
    events:
      - http:
          path: /import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
          authorizer:
            name: basicAuthorizer
            arn: arn:aws:lambda:ap-south-1:792855711714:function:authorization-service-dev-basicAuthorizer
            resultTtlInSeconds: 0
            type: request
  importFileParser:
    handler: importFileParser.importFileParser
    events:
      - s3:
          bucket: ${self:provider.environment.S3_BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
